# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cde21490eae609b26a2e0a060fc08b8647fce87a6aacfdc57fd48525d3df91ccadd58d558cb46964d0a33de0c8b28165ba5fbb6ebf75bb7874897b72fe02ef2

test:
  secret_key_base: 25ae3f0fca93a774a3f80e75d3387b8d9c61b63f4d7911763b9c5a0f0aaa17322e94aab214f8181e66ca0389e5d6c8fa4169bc00d1acd2ff861c32622f8eb6c4
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
